// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gszlydxwbknpcrqabnkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzemx5ZHh3YmtucGNycWFibmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDQ5ODUsImV4cCI6MjA3MDMyMDk4NX0.U4Cvc1lAULu97vvv0s7n2ZqG2WeyhiTvDUD0q_yxdbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});